Objetivo 2 Realizado
NachoCarher/MyHams pull request #17
Opened 2021-11-05 08:59 UTC by Parka015

Se han desarrollado los fuentes y se encuentran en modules y se ha añadido el archivo yaml

2021-11-05 10:43 UTC, JJ requested changes
Los cambios en el código tienen que referirse a un issue, y este debe expresar un problema. Se ruega también a @NachoCarher que asigne este PR y los issues con los que (posiblemente) trata al milestone que corresponda.

2021-11-05 10:43 UTC, JJ commented on iv.yaml
> +entidad: modules/productos.py
Esto está mal, y lo dijimos en clase (aparte de copiado de otros que también están mal). Por favor, consulta la guía de YAML.

2021-11-05 12:32 UTC, Parka015 commented on iv.yaml
> +entidad: modules/productos.py
Lo de yaml soy culpable, voy a mirarlo. En cuanto al código he tratado de escoger la mejor estructura de clases que resuelvan el HU4 que esta en el M1, con lo cual el código se refiere al issue HU4. El problema que resuelve es que sin estructura de datos no hay donde guardar nada.

2021-11-05 12:55 UTC, JJ commented on iv.yaml
> +entidad: modules/productos.py
Ya, pero lo que tiene que contener el issue es el problema, y el código la solución.

2021-11-05 15:13 UTC, Parka015 commented on iv.yaml
> +entidad: modules/productos.py
Entonces de la parte que he entregado yo, que cosas estan mal?

2021-11-05 16:10 UTC, JJ commented on iv.yaml
> +entidad: modules/productos.py
> Los cambios en el código tienen que referirse a un issue, y este debe expresar un problema.

2021-11-05 22:10 UTC, Parka015 commented on iv.yaml
> +entidad: modules/productos.py
Con los cambios que he realizado, soluciono ambos problemas ?

2021-11-06 09:13 UTC, JJ commented on iv.yaml
> +entidad: modules/productos.py
¿Qué cambios? https://github.com/NachoCarher/MyHams/pull/17/commits/2a3c2f6e1870235e12908422c1b1d24872083573 pone update iv.yaml y sigue sin referirse a ningún issue. Por favor, pedid también explícitamente que se revise.

2021-11-06 10:34 UTC, Parka015 commented on iv.yaml
> +entidad: modules/productos.py
Habia tocado la descripción del issue porque pensaba que te referias a eso.
Como dices que "el issue tiene que expresar un problema", he tocado el issue, no el Archivo yaml.
Y como se supone que ponga en el archivo yaml a que issue hace referencia? O te refieres que el commit diga expresamente a que issue hace referencia ?
Es que estos detalles ni vienen en el guión como tal ni en las páginas donde busco y voy a ciegas probando cosas

2021-11-06 10:53 UTC, JJ commented on iv.yaml
> +entidad: modules/productos.py
Vamos a ver, Pablo. Si vas a ciegas subiendo cosas, no las subas. Cada cosa que subes tiene que ser evaluada y corregida, y tengo que invertir tiempo en ello. Ya en el [objetivo 1](http://jj.github.io/IV/documentos/proyecto/1.Infraestructura#explicaci%C3%B3n) dice claramente que los mensajes de commits tienen que referir a un issue. No lo has hecho en ninguno de los dos. Tienes [toda una lista de comprobación de este objetivo](http://jj.github.io/IV/documentos/proyecto/2.Entidad#lista-de-comprobaci%C3%B3n), ¿la has pasado por lo que has hecho? ¿Crees que por cambiar el contenido de un issue que no referencias en ningún código creado está solucionado el problema?

2021-11-09 14:36 UTC, Parka015 commented on iv.yaml
> +entidad: modules/productos.py
@JJ  Listo para revisar Objetivo 2

2021-11-09 15:45 UTC, JJ requested changes
Aparte de los problemas indicados, y el hecho de que el código no está desarrollado desde un issue y un HU (y por eso quedan funciones que usan atributos inexistentes), hay ficheros pyc que no tenían que estar en el repo y que evidencian la mala práctica de usar "git add *" o "git add .".
Sería conveniente también que @NachoCarher diera algún tipo de feedback sobre el tema.

2021-11-09 15:45 UTC, JJ commented on modules/producto.py
> +        return self.en_venta
¿Cómo puedes referirte a atributos que ya no existen?

2021-11-09 15:45 UTC, JJ commented on modules/productoVenta.py
> +a = productoVenta ("patata", "Verdura", 10, 20)
No introduzcáis código ejecutable en las clases.

2021-11-11 19:31 UTC, Parka015 commented
@JJ Listo para revisión

2021-11-11 19:39 UTC, JJ approved these changes
Buena organización de la jerarquía de clases, y mucho mejor el uso de mensajes de commit. Todavía deberían contribuir más a ser documentación, pero son aceptables.

2021-11-11 19:56 UTC, Parka015 commented
> Buena organización de la jerarquía de clases, y mucho mejor el uso de mensajes de commit. Todavía deberían contribuir más a ser documentación, pero son aceptables.

Una cosa que acabo de hacer es cerrar mi issue, y usar el que tenia nacho (este #13 ) porque a fin de cuentas trataban de resolver el mismo problema

2021-12-10 12:27 UTC, merged