[IV-21-22] Objetivo 1
NachoCarher/MyHams pull request #3
Opened 2021-10-02 19:11 UTC by NachoCarher

2021-10-05 10:28 UTC, JJ requested changes
La primera propuesta, BeAShark, tenía más o menos apariencia de tener una cierta lógica de negocio. Esta no. Hiciste un nuevo PR y lo fusionaste sin ningún tipo de retroalimentación. Puedes hacerlo, puesto que el objetivo 0 estaba ya superado. Pero si cambias todo, incluyes un problema sin ninguna lógica de negocio, no va a poder considerarse para este objetivo. Revisa el objetivo 0, y cambia este de forma que o ese problema o el que planteaste primero tenga, de verdad, una lógica de negocio que se pueda usar.

2021-10-06 10:54 UTC, NachoCarher commented
@JJ he editado la descripción del proyecto. Bajo mi punto de vista ya tiene una lógica de negocio. Ahora un usuario puede por ejemplo proporcionar entradas sobre su inventario y el sistema ofrecer datos estadísticos sobre predicción de ventas.

2021-10-07 11:49 UTC, JJ commented on README.md
> +## Descripción del problema 🛠️
Potencialmente, se ve que este problema tiene una lógica de negocio suficiente. Pero no está nada claro cuál es. Usas verbos vagos como "incrementar las ventas" (¿de qué forma y en base a qué información?) "mejorar la gestión" (¿de qué forma?) "reducir errores" (¿qué errores?)
Está genial que uses problemas cercanos, porque eso te puede ayudar a empatizar, pero en la descripción del mismo y la solución posible tienes que ser bastante concreto, y más en este momento que ya estamos en el objetivo 1

2021-10-14 10:33 UTC, NachoCarher commented on README.md
> +## Descripción del problema 🛠️
@JJ Aquí trato de ser más claro y contestar a las preguntas que usted me hizo para evitar lo de los verbos vagos y ser mas extenso y preciso.

- Incrementar las ventas:
	- ¿De qué forma?
		Identificación de los pedidos con mayor potencial de venta.
		Por ejemplo, el sistema debería recomendar aumentar el inventario de aquellos productos con ventas
		ocasionales pero que son muy baratos y rentables, y tambien recomendar aquellos que se venden mucho independientemente del precio porque acaban aportando un buen beneficio.
		

	- ¿En base a qué información?
		El sistema debe recibir como entrada un histórico o una serie de datos del negocio. 
		Como el precio al por mayor que tienen los productos, la cantidad encargada, la frecuencia con la que se hacen pedidos de un determindado producto, porcentaje de existencias vendidas a final de mes, precio de venta.


- Mejorar la gestión:
	- ¿De qué forma?
		Con los datos recabados el sistema reconocerá que productos podrían venderse más y cuáles son prescindibles por su baja rentabilidad.
		Se muestra un pronóstico de la evolución del índice de ventas si se aplicasen las recomendaciones aportadas por la aplicación.
		La gestión se ve favorablemente afectada debido a que con el simple hecho de usar la aplicación ya se está recogiendo el inventario del negocio y está simplificando al usuario final su visualización y control de existencias.

- Reducir errores:
	- ¿Cuáles?
		Considero que es un error el hecho de no saber identificar que productos son los que provocan pérdidas en un negocio. Y a veces puede ser
		difícil reconocerlos puesto a que las pérdidas pueden ser ínfimas u ofrecer un rendimiento muy irregular con altos márgenes positivos y negativos.

2021-11-05 08:57 UTC, JJ requested changes
Te estás acercando más, pero por favor mira la lista de comprobación sobre milestones e issues y pon sólo los que reúnan esas características. Ya te lo he indicado en los correpsondientes (y @parka15) también.

2021-11-10 12:42 UTC, NachoCarher commented
@JJ Entonces si #13 no se considera como una HU y es un issue, el milestone inicial necesitaría tener un producto mínimamente viable. Me has comentado en la HU2 (#7) que debería usar #13 cómo issue y que tendría que asignarla al milestone inicial. He asignado HU2 al M0, sin embargo no entiendo a qué se refiere eso de usar #13 cómo issue, ¿irían ambos en el mismo milestone? Si están ligados entre ellos considero que sí y de momento así lo he puesto.

2021-11-11 09:10 UTC, NachoCarher commented
@JJ cómo me has comentado en clase, para poder comenzar con el desarrollo de software es necesario que el primer milestone tenga una HU con un issue que resolver. Ya he entendido el que #7 use #13 cómo issue, he referenciado dicha HU desde el propio issue y ambos se corresponden con el milestone inicial, tal y como me explicaste. 

Creo que es viable para @Parka015 comenzar con el desarrollo de forma correcta y considero que el Objetivo 1 está cubierto.

2021-11-11 19:33 UTC, JJ approved these changes
:+1:

2021-11-12 19:47 UTC, merged